env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: proji-darwin-amd64
    ldflags: -s -w -X github.com/proji/proji.Version={{.Version}} -X github.com/proji/proji.BuildDate={{.Date}} -X github.com/proji/proji.CommitHash={{ .ShortCommit }}
    binary: proji
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    main: ./cmd/proji/main.go
    goos:
      - darwin
    goarch:
      - amd64
  - id: proji-linux-amd64
    ldflags: -s -w -X github.com/proji/proji.Version={{.Version}} -X github.com/proji/proji.BuildDate={{.Date}} -X github.com/proji/proji.CommitHash={{ .ShortCommit }}
    binary: proji
    env:
      - CGO_ENABLED=1
    main: ./cmd/proji/main.go
    goos:
      - linux
    goarch:
      - amd64
  - id: proji-windows-amd64
    ldflags: -s -w -X github.com/proji/proji.Version={{.Version}} -X github.com/proji/proji.BuildDate={{.Date}} -X github.com/proji/proji.CommitHash={{ .ShortCommit }}
    binary: proji
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    main: ./cmd/proji/main.go
    goos:
      - windows
    goarch:
      - amd64
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
    files:
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
brews:
  - github:
      owner: nikoksr
      name: homebrew-taps
    commit_author:
      name: Niko Köser
      email: koeserniko@gmail.com
    folder: Formula
    homepage: "https://github.com/nikoksr/proji"
    install: |
      bin.install "proji"
    description: "A powerful cross-platform CLI project templating tool."
scoop:
  bucket:
    owner: nikoksr
    name: scoop-bucket
  commit_author:
    name: Niko Köser
    email: koeserniko@gmail.com
  homepage: "https://github.com/nikoksr/proji"
  description: "A powerful cross-platform CLI project templating tool."
  license: MIT
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch

nfpms:
  -
    id: proji-linux-amd64 
    package_name: proji
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      linux: Linux
    homepage: https://github.com/nikoksr/proji
    maintainer: Niko Köser <koeserniko@gmail.com>
    description: A powerful cross-platform CLI project templating tool.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin


snapcrafts: 
  -
    id: proji-linux-amd64 
    builds:
      - proji-linux-amd64 
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      linux: Linux
    publish: false
    description: A powerful cross-platform CLI project templating tool.
    summary: cross-platform CLI templating tool.
    confinement: classic
    license: MIT
    base: bare